package com.mff.entities;
// Generated Apr 22, 2023, 4:53:09 PM by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name = "likes", catalog = "malefashion")
public class Likes implements java.io.Serializable {

	private Integer id;
	private User user;
	private Videos videos;

//	jdbc: id -> obj
//	orm : -> obj
	public Likes() {
	}

	public Likes(User user, Videos videos) {
		this.user = user;
		this.videos = videos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idVideo", nullable = false)
	public Videos getVideos() {
		return this.videos;
	}

	public void setVideos(Videos videos) {
		this.videos = videos;
	}

}
